# Generated by Django 5.1.2 on 2024-10-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopListing',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('listing_image', models.URLField(blank=True, max_length=500)),
                ('total_views', models.IntegerField(default=0)),
                ('favorites', models.IntegerField(default=0)),
                ('listing_age', models.IntegerField(default=0)),
                ('daily_view', models.FloatField(default=0.0)),
                ('price', models.FloatField(default=0.0)),
                ('currency_code', models.CharField(blank=True, max_length=10)),
                ('currency_symbol', models.CharField(blank=True, max_length=5)),
                ('orig_price', models.FloatField(default=0.0)),
                ('est_sales_value', models.IntegerField(default=0)),
                ('est_sales_label', models.CharField(blank=True, max_length=50)),
                ('est_revenue_value', models.FloatField(default=0.0)),
                ('est_revenue_label', models.CharField(blank=True, max_length=50)),
                ('est_conversion_rate_value', models.FloatField(default=0.0)),
                ('est_conversion_rate_label', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'shop_listing',
            },
        ),
    ]
